spring.application.name=spring3
app.jwt.secret=change-me-to-a-long-random-secret-please
app.weather.base-url=https://api.open-meteo.com
app.weather.timeout=5

app.movie.base.url=https://api.movie.com
app.movie.apiKey=33