spring.application.name=e-com1
app.jwt.secret=change-me-to-a-long-random-secret-please
app.weather.base-url=https://api.open-meteo.com
app.weather.timeout=5

app.movie.base.url=https://api.movie.com
app.movie.apiKey=33

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
