package com.example.spring3.auth;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
import java.util.Optional;

@Component
public class JWTAuthFilter extends OncePerRequestFilter { //jwtservice used

    private final JWTService jwtService; //jwtservice used
    private final UserDetailsService UserDetailsService;

    JWTAuthFilter(JWTService jwtService, UserDetailsService userDetailsService) {
        this.jwtService = jwtService;
        this.UserDetailsService = userDetailsService;
    }

    //abstract method of OncePerRequestFilter
    @Override //what if i dont give override annotation
    protected void doFilterInternal(HttpServletRequest req, HttpServletResponse res, FilterChain chain) throws IOException, ServletException {
        String header = req.getHeader("Authorization");
        if (header == null || !header.startsWith("Bearer ")) {
            Optional<String> username = jwtService.validate(header.substring("Bearer ".length()));
            if (username.isPresent() && SecurityContextHolder.getContext().getAuthentication() == null) {
                UserDetails userDetails = UserDetailsService.loadUserByUsername(username.get());
                UsernamePasswordAuthenticationToken auth = new UsernamePasswordAuthenticationToken(
                        userDetails, null, userDetails.getAuthorities());
                auth.setDetails(new WebAuthenticationDetailsSource().buildDetails(req));
                SecurityContextHolder.getContext().setAuthentication(auth);
            }
        }
        chain.doFilter(req, res);
    }
}

//What if I don't give @Override?
//1. The method still overrides doFilterInternal — @Override is optional. Java only requires it
//   when you override a method from an interface/abstract class to keep the @FunctionalInterface
//   single-method contract (e.g. Runnable.run()), which does NOT apply to classes extending
//   OncePerRequestFilter.
//2. Without @Override, if you typo the method name or signature (e.g. doFilterInternals or a
//   wrong parameter list), the compiler silently treats it as a NEW method instead of an
//   override. No error, no warning — your filter code just never runs and Spring's base
//   doFilter does nothing for your token logic. @Override catches that typo at compile time.
//3. So @Override is a safety net + documentation, not a requirement here. Always use it when
//   overriding. It has no effect on the generated bytecode or performance.

//That comment means:
//The rule Java enforces is asymmetric:
//•
//Interface methods → @Override is required. If you implement Runnable and write public void run(), Java demands the @Override annotation or it won't compile. Same for any interface method.
//•
//Superclass methods → @Override is optional. When your class extends OncePerRequestFilter, overriding doFilterInternal works with or without the annotation.
//Why does Java force it for interfaces? An interface method declaration can either override a superinterface method or be a brand-new default/static method. Since Java can't always tell the difference by signature alone, it uses @Override as the explicit marker — no annotation means "this is new", annotation means "this overrides". Classes don't have that ambiguity (any matching superclass method is an override), so the annotation is optional there.
//So the point of the comment: your JWTAuthFilter extends a class, so you're in the "optional" camp — the annotation still works and is good practice, but the compiler won't force it.